version: '3.8'

services:
  app:
    build: .
    ports:
      - "9000:9000"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - API_KEY=$API_KEY
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=booking_platform
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: